variables:
  #MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: sgmia/maven:latest

before_scipt:
  - zipinfo /cache/$CI_PROJECT_PATH/$CI_BUILD_NAME/cache.zip
  - zipinfo /cache/$CI_PROJECT_PATH/global/cache.zip
  
after_scipt:
  - zipinfo /cache/$CI_PROJECT_PATH/$CI_BUILD_NAME/cache.zip
  - zipinfo /cache/$CI_PROJECT_PATH/global/cache.zip

cache:
  key: "global"
  paths:
  - .m2/
  
build:
  stage: build
  script:
  - 'mvn $MAVEN_CLI_OPTS compile'

test:
  stage: test
  script:
  - 'mvn $MAVEN_CLI_OPTS verify'

deploy:
  stage: deploy
  script:
  - 'mvn $MAVEN_CLI_OPTS -Dmaven.test.skip=true install'
